// ============================================================================
// SHARED EMOJI PICKER MODULE
// ============================================================================

(function() {
    'use strict';

    // Emoji data organized by category
    const emojiData = {
        special: {
            name: '⭐ Special',
            emojis: [
                { emoji: '🐨', title: 'Koala', search: 'koala' },
                { emoji: '🐴', title: 'Horse', search: 'horse' },
                { emoji: '👨', title: 'Dad', search: 'dad father' },
                { emoji: '🌙', title: 'Luna', search: 'luna moon' },
                { emoji: '🚚', title: 'Truck', search: 'Truck' }
            ]
        },
        food: {
            name: '🍔 Food & Drink',
            emojis: [
                { emoji: '🍎', title: 'Apple' },
                { emoji: '🍊', title: 'Orange' },
                { emoji: '🍌', title: 'Banana' },
                { emoji: '🍇', title: 'Grapes' },
                { emoji: '🍓', title: 'Strawberry' },
                { emoji: '🥝', title: 'Kiwi' },
                { emoji: '🍉', title: 'Watermelon' },
                { emoji: '☕', title: 'Coffee' },
                { emoji: '🍵', title: 'Tea' },
                { emoji: '🍔', title: 'Burger' },
                { emoji: '🌭', title: 'Hot Dog' },
                { emoji: '🌮', title: 'Taco' },
                { emoji: '🌯', title: 'Burrito' },
                { emoji: '🍕', title: 'Pizza' },
                { emoji: '🍗', title: 'Chicken' },
                { emoji: '🍖', title: 'Meat on Bone' },
                { emoji: '🍰', title: 'Cake' },
                { emoji: '🧁', title: 'Cupcake' },
                { emoji: '🍪', title: 'Cookie' },
                { emoji: '🍩', title: 'Donut' },
                { emoji: '🥤', title: 'Drink' },
                { emoji: '🍺', title: 'Beer' },
                { emoji: '🍷', title: 'Wine' },
                { emoji: '🥂', title: 'Cheers' },
                { emoji: '🐟', title: 'Fish' },
                { emoji: '🦐', title: 'Shrimp' },
                { emoji: '🦞', title: 'Lobster' },
                { emoji: '🦀', title: 'Crab' },
                { emoji: '🥩', title: 'Meat' },
                { emoji: '🥓', title: 'Bacon' },
                { emoji: '🌾', title: 'Wheat' },
                { emoji: '🌽', title: 'Corn' },
                { emoji: '🥕', title: 'Carrot' },
                { emoji: '🥔', title: 'Potato' },
                { emoji: '🥬', title: 'Leafy Green' },
                { emoji: '🥒', title: 'Cucumber' },
                { emoji: '🥑', title: 'Avocado' },
                { emoji: '🍞', title: 'Bread' },
                { emoji: '🥐', title: 'Croissant' },
                { emoji: '🥨', title: 'Pretzel' },
                { emoji: '🧀', title: 'Cheese' },
                { emoji: '🥚', title: 'Egg' },
                { emoji: '🥛', title: 'Milk' },
                { emoji: '🥞', title: 'Pancakes' },
                { emoji: '🧇', title: 'Waffle' },
                { emoji: '🥯', title: 'Bagel' },
                { emoji: '🥖', title: 'Baguette' },
                { emoji: '🥪', title: 'Sandwich' },
                { emoji: '🥙', title: 'Stuffed Flatbread' },
                { emoji: '🧆', title: 'Falafel' },
                { emoji: '🥘', title: 'Shallow Pan of Food' },
                { emoji: '🍲', title: 'Pot of Food' },
                { emoji: '🍱', title: 'Bento Box' },
                { emoji: '🍘', title: 'Rice Cracker' },
                { emoji: '🍙', title: 'Rice Ball' },
                { emoji: '🍚', title: 'Cooked Rice' },
                { emoji: '🍛', title: 'Curry Rice' },
                { emoji: '🍜', title: 'Steaming Bowl' },
                { emoji: '🍝', title: 'Spaghetti' },
                { emoji: '🍠', title: 'Roasted Sweet Potato' },
                { emoji: '🍢', title: 'Oden' },
                { emoji: '🍣', title: 'Sushi' },
                { emoji: '🍤', title: 'Fried Shrimp' },
                { emoji: '🍥', title: 'Fish Cake' },
                { emoji: '🥮', title: 'Moon Cake' },
                { emoji: '🍡', title: 'Dango' },
                { emoji: '🥟', title: 'Dumpling' },
                { emoji: '🥠', title: 'Fortune Cookie' },
                { emoji: '🥡', title: 'Takeout Box' },
                { emoji: '🧈', title: 'Butter' },
                { emoji: '🧂', title: 'Salt' },
                { emoji: '🥜', title: 'Peanuts' },
                { emoji: '🌰', title: 'Chestnut' },
                { emoji: '🍯', title: 'Honey Pot' },
                { emoji: '🥄', title: 'Spoon' },
                { emoji: '🍴', title: 'Fork and Knife' },
                { emoji: '🍽️', title: 'Fork and Knife with Plate' },
                { emoji: '🥣', title: 'Bowl with Spoon' },
                { emoji: '🥃', title: 'Tumbler Glass' },
                { emoji: '🧃', title: 'Beverage Box' },
                { emoji: '🧉', title: 'Mate' },
                { emoji: '🧊', title: 'Ice' }
            ]
        },
        buildings: {
            name: '🏢 Buildings & Places',
            emojis: [
                { emoji: '🏪', title: 'Store' },
                { emoji: '🏬', title: 'Department Store' },
                { emoji: '🏭', title: 'Factory' },
                { emoji: '🏢', title: 'Office' },
                { emoji: '🏨', title: 'Hotel' },
                { emoji: '🏦', title: 'Bank' },
                { emoji: '🏥', title: 'Hospital' },
                { emoji: '🏫', title: 'School' },
                { emoji: '🎓', title: 'Graduation Cap' },
                { emoji: '🏰', title: 'Castle' },
                { emoji: '🏯', title: 'Japanese Castle' },
                { emoji: '🏛️', title: 'Building' },
                { emoji: '⛪', title: 'Church' },
                { emoji: '🕌', title: 'Mosque' },
                { emoji: '🕍', title: 'Synagogue' },
                { emoji: '🛕', title: 'Temple' },
                { emoji: '🏗️', title: 'Construction' },
                { emoji: '🚧', title: 'Construction Sign' },
                { emoji: '⛏️', title: 'Pick' },
                { emoji: '🔨', title: 'Hammer' },
                { emoji: '⚒️', title: 'Hammer and Pick' },
                { emoji: '🛠️', title: 'Hammer and Wrench' },
                { emoji: '🔩', title: 'Nut and Bolt' },
                { emoji: '⚙️', title: 'Gear' },
                { emoji: '🧰', title: 'Toolbox' },
                { emoji: '🔧', title: 'Wrench' },
                { emoji: '🪚', title: 'Saw' },
                { emoji: '🪓', title: 'Axe' },
                { emoji: '🪣', title: 'Bucket' },
                { emoji: '🧱', title: 'Brick' },
                { emoji: '🪵', title: 'Wood' },
                { emoji: '🪨', title: 'Rock' },
                { emoji: '🏠', title: 'House' },
                { emoji: '🏡', title: 'House with Garden' },
                { emoji: '🏘️', title: 'Houses' },
                { emoji: '🏚️', title: 'Derelict House' },
                { emoji: '⛺', title: 'Tent' },
                { emoji: '🏕️', title: 'Camping' },
                { emoji: '🏖️', title: 'Beach' },
                { emoji: '🏝️', title: 'Desert Island' },
                { emoji: '🏜️', title: 'Desert' },
                { emoji: '🌆', title: 'Cityscape at Dusk' },
                { emoji: '🌇', title: 'Sunset' },
                { emoji: '🌃', title: 'Night with Stars' }
            ]
        },
        vehicles: {
            name: '🚗 Vehicles',
            emojis: [
                { emoji: '🚗', title: 'Car' },
                { emoji: '🚕', title: 'Taxi' },
                { emoji: '🚙', title: 'SUV' },
                { emoji: '🚐', title: 'Van' },
                { emoji: '🛻', title: 'Pickup Truck' },
                { emoji: '🚚', title: 'Truck' },
                { emoji: '🚛', title: 'Articulated Lorry' },
                { emoji: '🚜', title: 'Tractor' },
                { emoji: '🏎️', title: 'Racing Car' },
                { emoji: '🏍️', title: 'Motorcycle' },
                { emoji: '🛵', title: 'Scooter' },
                { emoji: '🚲', title: 'Bicycle' },
                { emoji: '🛴', title: 'Kick Scooter' },
                { emoji: '🛹', title: 'Skateboard' },
                { emoji: '🛼', title: 'Roller Skate' },
                { emoji: '🚢', title: 'Ship' },
                { emoji: '⛴️', title: 'Ferry' },
                { emoji: '🛥️', title: 'Motor Boat' },
                { emoji: '🚤', title: 'Speedboat' },
                { emoji: '⛵', title: 'Sailboat' },
                { emoji: '✈️', title: 'Plane' },
                { emoji: '🛩️', title: 'Small Plane' },
                { emoji: '🛫', title: 'Airplane Departure' },
                { emoji: '🛬', title: 'Airplane Arrival' },
                { emoji: '🚁', title: 'Helicopter' },
                { emoji: '🪂', title: 'Parachute' },
                { emoji: '💺', title: 'Seat' },
                { emoji: '🚟', title: 'Suspension Railway' },
                { emoji: '🚠', title: 'Mountain Cableway' },
                { emoji: '🚡', title: 'Aerial Tramway' },
                { emoji: '🚀', title: 'Rocket' },
                { emoji: '🛸', title: 'UFO' },
                { emoji: '🚂', title: 'Train' },
                { emoji: '🚃', title: 'Railway Car' },
                { emoji: '🚄', title: 'High-Speed Train' },
                { emoji: '🚅', title: 'Bullet Train' },
                { emoji: '🚆', title: 'Train' },
                { emoji: '🚇', title: 'Metro' },
                { emoji: '🚈', title: 'Light Rail' },
                { emoji: '🚉', title: 'Station' },
                { emoji: '🚊', title: 'Tram' },
                { emoji: '🚝', title: 'Monorail' },
                { emoji: '🚞', title: 'Mountain Railway' },
                { emoji: '🚌', title: 'Bus' },
                { emoji: '🚍', title: 'Oncoming Bus' },
                { emoji: '🚎', title: 'Trolleybus' },
                { emoji: '🚑', title: 'Ambulance' },
                { emoji: '🚒', title: 'Fire Engine' },
                { emoji: '🚓', title: 'Police Car' },
                { emoji: '🚔', title: 'Oncoming Police Car' },
                { emoji: '🚨', title: 'Rotating Light' },
                { emoji: '⛽', title: 'Gas' },
                { emoji: '🛣️', title: 'Motorway' },
                { emoji: '🛤️', title: 'Railway Track' },
                { emoji: '🛢️', title: 'Oil Drum' },
                { emoji: '🛳️', title: 'Passenger Ship' },
                { emoji: '🚏', title: 'Bus Stop' }
            ]
        },
        business: {
            name: '💰 Money & Business',
            emojis: [
                { emoji: '💰', title: 'Money' },
                { emoji: '💴', title: 'Yen' },
                { emoji: '💵', title: 'Dollar' },
                { emoji: '💶', title: 'Euro' },
                { emoji: '💷', title: 'Pound' },
                { emoji: '💸', title: 'Money with Wings' },
                { emoji: '💳', title: 'Credit Card' },
                { emoji: '💎', title: 'Diamond' },
                { emoji: '💍', title: 'Ring' },
                { emoji: '💼', title: 'Briefcase' },
                { emoji: '🧳', title: 'Luggage' },
                { emoji: '📊', title: 'Chart' },
                { emoji: '📈', title: 'Growth' },
                { emoji: '📉', title: 'Decrease' },
                { emoji: '📋', title: 'Clipboard' },
                { emoji: '📌', title: 'Pushpin' },
                { emoji: '📍', title: 'Round Pushpin' },
                { emoji: '📦', title: 'Package' },
                { emoji: '📨', title: 'Incoming Envelope' },
                { emoji: '📧', title: 'Email' },
                { emoji: '📮', title: 'Postbox' },
                { emoji: '🛒', title: 'Shopping Cart' },
                { emoji: '🛍️', title: 'Shopping Bags' },
                { emoji: '🛎️', title: 'Bellhop Bell' },
                { emoji: '🏷️', title: 'Label' },
                { emoji: '🎫', title: 'Ticket' },
                { emoji: '🎟️', title: 'Admission Tickets' },
                { emoji: '📞', title: 'Telephone Receiver' },
                { emoji: '📠', title: 'Fax Machine' },
                { emoji: '📪', title: 'Closed Mailbox' },
                { emoji: '📫', title: 'Open Mailbox' },
                { emoji: '📬', title: 'Mailbox with Mail' },
                { emoji: '📭', title: 'Mailbox with No Mail' },
                { emoji: '📯', title: 'Postal Horn' },
                { emoji: '📩', title: 'Envelope with Arrow' },
                { emoji: '📤', title: 'Outbox Tray' },
                { emoji: '📥', title: 'Inbox Tray' },
                { emoji: '📝', title: 'Memo' },
                { emoji: '📄', title: 'Document' },
                { emoji: '📃', title: 'Page with Curl' },
                { emoji: '📑', title: 'Bookmark Tabs' },
                { emoji: '📒', title: 'Ledger' },
                { emoji: '📓', title: 'Notebook' },
                { emoji: '📔', title: 'Notebook with Decorative Cover' },
                { emoji: '📕', title: 'Closed Book' },
                { emoji: '📗', title: 'Green Book' },
                { emoji: '📘', title: 'Blue Book' },
                { emoji: '📙', title: 'Orange Book' },
                { emoji: '📚', title: 'Books' },
                { emoji: '📖', title: 'Open Book' },
                { emoji: '🔖', title: 'Bookmark' }
            ]
        },
        entertainment: {
            name: '🎪 Entertainment',
            emojis: [
                { emoji: '🎪', title: 'Circus' },
                { emoji: '🎭', title: 'Theater' },
                { emoji: '🎨', title: 'Art' },
                { emoji: '🎬', title: 'Movie' },
                { emoji: '🎤', title: 'Microphone' },
                { emoji: '🎧', title: 'Headphone' },
                { emoji: '🎼', title: 'Musical Score' },
                { emoji: '🎹', title: 'Musical Keyboard' },
                { emoji: '🥁', title: 'Drum' },
                { emoji: '🎷', title: 'Saxophone' },
                { emoji: '🎺', title: 'Trumpet' },
                { emoji: '🎻', title: 'Violin' },
                { emoji: '🎵', title: 'Music' },
                { emoji: '🎶', title: 'Musical Notes' },
                { emoji: '🎮', title: 'Game' },
                { emoji: '🕹️', title: 'Joystick' },
                { emoji: '🎯', title: 'Target' },
                { emoji: '🎳', title: 'Bowling' },
                { emoji: '🎰', title: 'Slot' },
                { emoji: '🎲', title: 'Dice' },
                { emoji: '🃏', title: 'Joker' },
                { emoji: '🀄', title: 'Mahjong' },
                { emoji: '🎴', title: 'Playing Cards' },
                { emoji: '🎟️', title: 'Admission Tickets' },
                { emoji: '🎫', title: 'Ticket' }
            ]
        },
        technology: {
            name: '📱 Technology',
            emojis: [
                { emoji: '📱', title: 'Phone' },
                { emoji: '📲', title: 'Mobile Phone with Arrow' },
                { emoji: '☎️', title: 'Telephone' },
                { emoji: '📞', title: 'Telephone Receiver' },
                { emoji: '📟', title: 'Pager' },
                { emoji: '📠', title: 'Fax Machine' },
                { emoji: '💻', title: 'Computer' },
                { emoji: '🖥️', title: 'Desktop Computer' },
                { emoji: '🖨️', title: 'Printer' },
                { emoji: '⌨️', title: 'Keyboard' },
                { emoji: '🖱️', title: 'Computer Mouse' },
                { emoji: '🖲️', title: 'Trackball' },
                { emoji: '💾', title: 'Floppy Disk' },
                { emoji: '💿', title: 'Optical Disk' },
                { emoji: '📀', title: 'DVD' },
                { emoji: '📺', title: 'TV' },
                { emoji: '📻', title: 'Radio' },
                { emoji: '📷', title: 'Camera' },
                { emoji: '📸', title: 'Camera with Flash' },
                { emoji: '📹', title: 'Video Camera' },
                { emoji: '🎥', title: 'Movie Camera' },
                { emoji: '📼', title: 'Videocassette' },
                { emoji: '🔍', title: 'Magnifying Glass' },
                { emoji: '🔎', title: 'Magnifying Glass Tilted Right' },
                { emoji: '🔧', title: 'Tool' },
                { emoji: '⚡', title: 'Lightning' },
                { emoji: '🔌', title: 'Electric Plug' },
                { emoji: '💡', title: 'Light Bulb' },
                { emoji: '🔦', title: 'Flashlight' },
                { emoji: '🕯️', title: 'Candle' },
                { emoji: '🧯', title: 'Fire Extinguisher' },
                { emoji: '🪣', title: 'Bucket' },
                { emoji: '🧰', title: 'Toolbox' },
                { emoji: '🧲', title: 'Magnet' },
                { emoji: '🔬', title: 'Microscope' },
                { emoji: '🔭', title: 'Telescope' },
                { emoji: '📡', title: 'Satellite' }
            ]
        },
        symbols: {
            name: '⭐ Symbols & Status',
            emojis: [
                { emoji: '⭐', title: 'Star' },
                { emoji: '🌟', title: 'Glowing Star' },
                { emoji: '💫', title: 'Dizzy' },
                { emoji: '✨', title: 'Sparkles' },
                { emoji: '🔥', title: 'Fire' },
                { emoji: '💥', title: 'Explosion' },
                { emoji: '💢', title: 'Anger Symbol' },
                { emoji: '💯', title: 'Hundred Points' },
                { emoji: '✅', title: 'Check Mark' },
                { emoji: '❌', title: 'Cross Mark' },
                { emoji: '⭕', title: 'Heavy Large Circle' },
                { emoji: '🎯', title: 'Target' },
                { emoji: '🎪', title: 'Circus Tent' },
                { emoji: '🎨', title: 'Artist Palette' },
                { emoji: '🏆', title: 'Trophy' },
                { emoji: '🥇', title: '1st Place Medal' },
                { emoji: '🥈', title: '2nd Place Medal' },
                { emoji: '🥉', title: '3rd Place Medal' },
                { emoji: '🏅', title: 'Sports Medal' },
                { emoji: '🎖️', title: 'Military Medal' },
                { emoji: '👑', title: 'Crown' },
                { emoji: '💍', title: 'Ring' },
                { emoji: '💎', title: 'Gem' },
                { emoji: '🔑', title: 'Key' },
                { emoji: '🗝️', title: 'Old Key' },
                { emoji: '🎁', title: 'Gift' },
                { emoji: '🎀', title: 'Ribbon' },
                { emoji: '🎗️', title: 'Reminder Ribbon' },
                { emoji: '🏵️', title: 'Rosette' },
                { emoji: '🎟️', title: 'Admission Tickets' },
                { emoji: '🎫', title: 'Ticket' },
                { emoji: '🎖️', title: 'Medal' },
                { emoji: '🎗️', title: 'Reminder Ribbon' }
            ]
        },
        nature: {
            name: '🌳 Nature',
            emojis: [
                { emoji: '🌳', title: 'Tree' },
                { emoji: '🌲', title: 'Evergreen Tree' },
                { emoji: '🌴', title: 'Palm Tree' },
                { emoji: '🌱', title: 'Seedling' },
                { emoji: '🌿', title: 'Herb' },
                { emoji: '🍀', title: 'Four Leaf Clover' },
                { emoji: '🍃', title: 'Leaf' },
                { emoji: '🍂', title: 'Fallen Leaf' },
                { emoji: '🍁', title: 'Maple Leaf' },
                { emoji: '🌾', title: 'Sheaf of Rice' },
                { emoji: '🌷', title: 'Tulip' },
                { emoji: '🌹', title: 'Rose' },
                { emoji: '🌺', title: 'Hibiscus' },
                { emoji: '🌻', title: 'Sunflower' },
                { emoji: '🌼', title: 'Blossom' },
                { emoji: '🌸', title: 'Cherry Blossom' },
                { emoji: '🌍', title: 'Globe' },
                { emoji: '🌎', title: 'Globe Americas' },
                { emoji: '🌏', title: 'Globe Asia-Australia' },
                { emoji: '🗺️', title: 'Map' },
                { emoji: '🧭', title: 'Compass' },
                { emoji: '⛰️', title: 'Mountain' },
                { emoji: '🏔️', title: 'Snow-Capped Mountain' },
                { emoji: '🌋', title: 'Volcano' },
                { emoji: '🏕️', title: 'Camping' },
                { emoji: '🏖️', title: 'Beach' },
                { emoji: '🏜️', title: 'Desert' },
                { emoji: '🏝️', title: 'Desert Island' },
                { emoji: '🌊', title: 'Water Wave' },
                { emoji: '🌅', title: 'Sunrise' },
                { emoji: '🌄', title: 'Sunrise Over Mountains' },
                { emoji: '🌆', title: 'Cityscape at Dusk' },
                { emoji: '🌇', title: 'Sunset' },
                { emoji: '🌃', title: 'Night with Stars' },
                { emoji: '🌉', title: 'Bridge at Night' },
                { emoji: '🌌', title: 'Milky Way' },
                { emoji: '🌠', title: 'Shooting Star' },
                { emoji: '☀️', title: 'Sun' },
                { emoji: '🌤️', title: 'Sun Behind Small Cloud' },
                { emoji: '⛅', title: 'Sun Behind Cloud' },
                { emoji: '🌥️', title: 'Sun Behind Large Cloud' },
                { emoji: '☁️', title: 'Cloud' },
                { emoji: '⛈️', title: 'Cloud with Lightning and Rain' },
                { emoji: '🌦️', title: 'Sun Behind Rain Cloud' },
                { emoji: '🌧️', title: 'Cloud with Rain' },
                { emoji: '⛈️', title: 'Thunder Cloud and Rain' },
                { emoji: '❄️', title: 'Snowflake' },
                { emoji: '☃️', title: 'Snowman' },
                { emoji: '⛄', title: 'Snowman Without Snow' },
                { emoji: '🌨️', title: 'Cloud with Snow' },
                { emoji: '🌩️', title: 'Cloud with Lightning' },
                { emoji: '🌪️', title: 'Tornado' },
                { emoji: '🌈', title: 'Rainbow' },
                { emoji: '☔', title: 'Umbrella with Rain Drops' },
                { emoji: '💧', title: 'Droplet' },
                { emoji: '☂️', title: 'Umbrella' }
            ]
        },
        documents: {
            name: '📄 Documents & Items',
            emojis: [
                { emoji: '📄', title: 'Document' },
                { emoji: '📃', title: 'Page with Curl' },
                { emoji: '📑', title: 'Bookmark Tabs' },
                { emoji: '📊', title: 'Bar Chart' },
                { emoji: '📈', title: 'Chart Increasing' },
                { emoji: '📉', title: 'Chart Decreasing' },
                { emoji: '📋', title: 'Clipboard' },
                { emoji: '📝', title: 'Memo' },
                { emoji: '📌', title: 'Pushpin' },
                { emoji: '📍', title: 'Round Pushpin' },
                { emoji: '📎', title: 'Paperclip' },
                { emoji: '🖇️', title: 'Linked Paperclips' },
                { emoji: '📏', title: 'Straight Ruler' },
                { emoji: '📐', title: 'Triangular Ruler' },
                { emoji: '✂️', title: 'Scissors' },
                { emoji: '🗂️', title: 'Card Index Dividers' },
                { emoji: '🗃️', title: 'Card File Box' },
                { emoji: '🗄️', title: 'File Cabinet' },
                { emoji: '🗑️', title: 'Wastebasket' },
                { emoji: '🧪', title: 'Science' },
                { emoji: '🧫', title: 'Petri Dish' },
                { emoji: '🧬', title: 'DNA' },
                { emoji: '🔬', title: 'Microscope' },
                { emoji: '🔭', title: 'Telescope' },
                { emoji: '📡', title: 'Satellite Antenna' },
                { emoji: '💉', title: 'Syringe' },
                { emoji: '💊', title: 'Pill' },
                { emoji: '🩹', title: 'Adhesive Bandage' },
                { emoji: '🩺', title: 'Stethoscope' },
                { emoji: '🚪', title: 'Door' },
                { emoji: '🛏️', title: 'Bed' },
                { emoji: '🛋️', title: 'Couch and Lamp' },
                { emoji: '🚽', title: 'Toilet' },
                { emoji: '🚿', title: 'Shower' },
                { emoji: '🛁', title: 'Bathtub' },
                { emoji: '🧴', title: 'Lotion Bottle' },
                { emoji: '🧷', title: 'Safety Pin' },
                { emoji: '🧹', title: 'Broom' },
                { emoji: '🧺', title: 'Basket' },
                { emoji: '🧻', title: 'Roll of Paper' },
                { emoji: '🧼', title: 'Soap' },
                { emoji: '🧽', title: 'Sponge' },
                { emoji: '🧯', title: 'Fire Extinguisher' },
                { emoji: '🛒', title: 'Shopping Cart' }
            ]
        },
        landmarks: {
            name: '🗼 Landmarks',
            emojis: [
                { emoji: '🗼', title: 'Tokyo Tower' },
                { emoji: '🗽', title: 'Statue of Liberty' },
                { emoji: '⛲', title: 'Fountain' },
                { emoji: '🎡', title: 'Ferris Wheel' },
                { emoji: '🎢', title: 'Roller Coaster' },
                { emoji: '🏟️', title: 'Stadium' }
            ]
        }
    };

    /**
     * Generate emoji picker HTML
     * @param {string} containerId - ID of the container element (default: 'emojiGridContainer')
     * @returns {string} HTML string for the emoji picker
     */
    function generateEmojiPickerHTML(containerId = 'emojiGridContainer') {
        let html = '<div class="emoji-search">';
        html += '<input type="text" id="emojiSearchInput" placeholder="🔍 Search emojis..." oninput="filterEmojis()">';
        html += '</div>';
        html += `<div id="${containerId}">`;

        // Generate HTML for each category
        for (const [categoryKey, categoryData] of Object.entries(emojiData)) {
            html += `<div class="emoji-category" data-category="${categoryKey}">${categoryData.name}</div>`;
            html += `<div class="emoji-grid" data-category="${categoryKey}">`;
            
            categoryData.emojis.forEach(emojiItem => {
                const searchAttr = emojiItem.search ? `data-search="${emojiItem.search}"` : '';
                html += `<button type="button" class="emoji-btn" onclick="selectEmoji('${emojiItem.emoji}')" title="${emojiItem.title}" data-category="${categoryKey}" ${searchAttr}>${emojiItem.emoji}</button>`;
            });
            
            html += '</div>';
        }

        html += '</div>';
        return html;
    }

    /**
     * Initialize emoji picker in a container
     * @param {string} containerId - ID of the container element (default: 'emojiPicker')
     */
    function initializeEmojiPicker(containerId = 'emojiPicker') {
        const container = document.getElementById(containerId);
        if (!container) {
            console.warn(`Emoji picker container with ID "${containerId}" not found`);
            return;
        }

        // Check if already initialized
        if (container.querySelector('.emoji-search')) {
            return;
        }

        container.innerHTML = generateEmojiPickerHTML('emojiGridContainer');
    }

    // Export functions to global scope
    window.generateEmojiPickerHTML = generateEmojiPickerHTML;
    window.initializeEmojiPicker = initializeEmojiPicker;
    window.emojiPickerData = emojiData; // Expose data for potential future use

})();